# Seed data for CrediLens - 38 iPhone products
# This file is used to populate the PostgreSQL database on Render

SEED_PRODUCTS = [
    {'company_name': 'Apple', 'product_name': 'iPhone X', 'batch_number': 'IMPORT-2017', 'category': 'Smartphone', 'processor_score': 497740.0, 'ram_gb': 3, 'storage_gb': 64, 'battery_mah': 2716, 'screen_inches': 5.8, 'camera_mp': 12.0, 'price_usd': 999.0, 'weight_g': 174.0, 'ideal_score': 20.28, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 8', 'batch_number': 'IMPORT-2017', 'category': 'Smartphone', 'processor_score': 497740.0, 'ram_gb': 2, 'storage_gb': 64, 'battery_mah': 1821, 'screen_inches': 4.7, 'camera_mp': 12.0, 'price_usd': 699.0, 'weight_g': 148.0, 'ideal_score': 19.94, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 8 Plus', 'batch_number': 'IMPORT-2017', 'category': 'Smartphone', 'processor_score': 497740.0, 'ram_gb': 3, 'storage_gb': 64, 'battery_mah': 2691, 'screen_inches': 5.5, 'camera_mp': 12.0, 'price_usd': 799.0, 'weight_g': 202.0, 'ideal_score': 20.01, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone XR', 'batch_number': 'IMPORT-2018', 'category': 'Smartphone', 'processor_score': 708193.0, 'ram_gb': 3, 'storage_gb': 64, 'battery_mah': 2942, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 749.0, 'weight_g': 194.0, 'ideal_score': 26.82, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone XS', 'batch_number': 'IMPORT-2018', 'category': 'Smartphone', 'processor_score': 708193.0, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 2658, 'screen_inches': 5.8, 'camera_mp': 12.0, 'price_usd': 999.0, 'weight_g': 177.0, 'ideal_score': 24.19, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone XS Max', 'batch_number': 'IMPORT-2018', 'category': 'Smartphone', 'processor_score': 708193.0, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 3174, 'screen_inches': 6.5, 'camera_mp': 12.0, 'price_usd': 1099.0, 'weight_g': 208.0, 'ideal_score': 29.05, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 11', 'batch_number': 'IMPORT-2019', 'category': 'Smartphone', 'processor_score': 925787.0, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 3110, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 699.0, 'weight_g': 194.0, 'ideal_score': 34.51, 'processor_model': 'Apple A13 Bionic', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/128GB/256GB', 'camera_sensor_main': 'Sony IMX 363 (12MP f/1.8)', 'camera_sensor_ultra': 'Samsung S5K4E6 (12MP f/2.4)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (3110mAh)', 'charging_watt': 5.0, 'display_type': 'Liquid Retina IPS LCD', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 11 Pro', 'batch_number': 'IMPORT-2019', 'category': 'Smartphone', 'processor_score': 925787.0, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 3046, 'screen_inches': 5.8, 'camera_mp': 12.0, 'price_usd': 999.0, 'weight_g': 188.0, 'ideal_score': 28.31, 'processor_model': 'Apple A13 Bionic', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/256GB/512GB', 'camera_sensor_main': 'Sony IMX 603 (12MP f/1.8)', 'camera_sensor_ultra': 'Samsung S5K4E6 (12MP f/2.0)', 'camera_sensor_telephoto': 'Samsung S5K3L6 (12MP f/2.0 2x)', 'battery_tech': 'Li-Ion (3046mAh)', 'charging_watt': 18.0, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 11 Pro Max', 'batch_number': 'IMPORT-2019', 'category': 'Smartphone', 'processor_score': 925787.0, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 3969, 'screen_inches': 6.5, 'camera_mp': 12.0, 'price_usd': 1099.0, 'weight_g': 226.0, 'ideal_score': 35.26, 'processor_model': 'Apple A13 Bionic', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/256GB/512GB', 'camera_sensor_main': 'Sony IMX 603 (12MP f/1.8)', 'camera_sensor_ultra': 'Samsung S5K4E6 (12MP f/2.0)', 'camera_sensor_telephoto': 'Samsung S5K3L6 (12MP f/2.0 2x)', 'battery_tech': 'Li-Ion (3969mAh)', 'charging_watt': 18.0, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone SE (2nd generation)', 'batch_number': 'IMPORT-2020', 'category': 'Smartphone', 'processor_score': 925787.0, 'ram_gb': 3, 'storage_gb': 64, 'battery_mah': 1821, 'screen_inches': 4.7, 'camera_mp': 12.0, 'price_usd': 399.0, 'weight_g': 148.0, 'ideal_score': 26.08, 'processor_model': 'Apple A13 Bionic', 'ram_type': '3GB LPDDR4X', 'storage_type': '64GB/128GB/256GB', 'camera_sensor_main': 'Sony IMX 363 (12MP f/1.8)', 'camera_sensor_ultra': None, 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (2342mAh)', 'charging_watt': 5.0, 'display_type': 'Retina IPS LCD', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 12 mini', 'batch_number': 'IMPORT-2020', 'category': 'Smartphone', 'processor_score': 1111665.0, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 2227, 'screen_inches': 5.4, 'camera_mp': 12.0, 'price_usd': 699.0, 'weight_g': 133.0, 'ideal_score': 32.62, 'processor_model': 'Apple A14 Bionic', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/128GB/256GB NVMe', 'camera_sensor_main': 'Sony IMX 553 (12MP f/1.6)', 'camera_sensor_ultra': 'Samsung S5K4E6 (12MP f/2.4)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (2227mAh)', 'charging_watt': 15.0, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 12', 'batch_number': 'IMPORT-2020', 'category': 'Smartphone', 'processor_score': 1111665.0, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 2815, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 799.0, 'weight_g': 164.0, 'ideal_score': 35.36, 'processor_model': 'Apple A14 Bionic', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/128GB/256GB NVMe', 'camera_sensor_main': 'Sony IMX 553 (12MP f/1.6)', 'camera_sensor_ultra': 'Samsung S5K4E6 (12MP f/2.4)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (2815mAh)', 'charging_watt': 15.0, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 12 Pro', 'batch_number': 'IMPORT-2020', 'category': 'Smartphone', 'processor_score': 1111665.0, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 2815, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 999.0, 'weight_g': 189.0, 'ideal_score': 43.22, 'processor_model': 'Apple A14 Bionic', 'ram_type': '6GB LPDDR4X', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX 603 (12MP f/1.6)', 'camera_sensor_ultra': 'Samsung S5K4E6 (12MP f/2.4)', 'camera_sensor_telephoto': 'Samsung S5K3L6 (12MP f/2.0 2x)', 'battery_tech': 'Li-Ion (2815mAh)', 'charging_watt': 15.0, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 12 Pro Max', 'batch_number': 'IMPORT-2020', 'category': 'Smartphone', 'processor_score': 1111665.0, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 3687, 'screen_inches': 6.7, 'camera_mp': 12.0, 'price_usd': 1099.0, 'weight_g': 228.0, 'ideal_score': 49.73, 'processor_model': 'Apple A14 Bionic', 'ram_type': '6GB LPDDR4X', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX 603 (12MP f/1.6)', 'camera_sensor_ultra': 'Samsung S5K4E6 (12MP f/2.4)', 'camera_sensor_telephoto': 'Samsung S5K3L6 (12MP f/2.0 2.5x)', 'battery_tech': 'Li-Ion (3687mAh)', 'charging_watt': 15.0, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 13 mini', 'batch_number': 'IMPORT-2021', 'category': 'Smartphone', 'processor_score': 1330956.0, 'ram_gb': 4, 'storage_gb': 128, 'battery_mah': 2438, 'screen_inches': 5.4, 'camera_mp': 12.0, 'price_usd': 699.0, 'weight_g': 140.0, 'ideal_score': 41.13, 'processor_model': 'Apple A15 Bionic', 'ram_type': '4GB LPDDR4X', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX 553 (12MP f/1.6)', 'camera_sensor_ultra': 'Samsung S5K3L6 (12MP f/2.4)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (2438mAh)', 'charging_watt': 20.0, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 13', 'batch_number': 'IMPORT-2021', 'category': 'Smartphone', 'processor_score': 1330956.0, 'ram_gb': 4, 'storage_gb': 128, 'battery_mah': 3227, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 799.0, 'weight_g': 174.0, 'ideal_score': 46.39, 'processor_model': 'Apple A15 Bionic', 'ram_type': '4GB LPDDR4X', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Sony IMX 553 (12MP f/1.6)', 'camera_sensor_ultra': 'Samsung S5K3L6 (12MP f/2.4)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (3240mAh)', 'charging_watt': 20.0, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 13 Pro', 'batch_number': 'IMPORT-2021', 'category': 'Smartphone', 'processor_score': 1330956.0, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 3095, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 999.0, 'weight_g': 204.0, 'ideal_score': 45.68, 'processor_model': 'Apple A15 Bionic', 'ram_type': '6GB LPDDR5', 'storage_type': '128GB/256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX 803 (12MP f/1.5)', 'camera_sensor_ultra': 'Sony IMX 553 (12MP f/1.8)', 'camera_sensor_telephoto': 'Samsung S5K3L6 (12MP f/2.8 3x)', 'battery_tech': 'Li-Ion (3095mAh)', 'charging_watt': 20.0, 'display_type': 'Super Retina XDR LTPO OLED', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 13 Pro Max', 'batch_number': 'IMPORT-2021', 'category': 'Smartphone', 'processor_score': 1330956.0, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 4352, 'screen_inches': 6.7, 'camera_mp': 12.0, 'price_usd': 1099.0, 'weight_g': 238.0, 'ideal_score': 53.31, 'processor_model': 'Apple A15 Bionic', 'ram_type': '6GB LPDDR5', 'storage_type': '128GB/256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX 803 (12MP f/1.5)', 'camera_sensor_ultra': 'Sony IMX 553 (12MP f/1.8)', 'camera_sensor_telephoto': 'Samsung S5K3L6 (12MP f/2.8 3x)', 'battery_tech': 'Li-Ion (4373mAh)', 'charging_watt': 20.0, 'display_type': 'Super Retina XDR LTPO OLED', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone SE (3rd generation)', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 1330956.0, 'ram_gb': 4, 'storage_gb': 64, 'battery_mah': 2018, 'screen_inches': 4.7, 'camera_mp': 12.0, 'price_usd': 429.0, 'weight_g': 144.0, 'ideal_score': 34.38, 'processor_model': 'Apple A15 Bionic', 'ram_type': '4GB LPDDR4X', 'storage_type': '64GB/128GB/256GB', 'camera_sensor_main': 'Sony IMX 363 (12MP f/1.8)', 'camera_sensor_ultra': None, 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (2460mAh)', 'charging_watt': 20.0, 'display_type': 'Retina IPS LCD', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 14', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 1469234.0, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 3279, 'screen_inches': 6.1, 'camera_mp': 12.0, 'price_usd': 799.0, 'weight_g': 172.0, 'ideal_score': 55.6, 'processor_model': 'Apple A15 Bionic', 'ram_type': '6GB LPDDR4X', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Samsung S5K3L6 (12MP f/1.5)', 'camera_sensor_ultra': 'Samsung ISOCELL JN1 (12MP f/2.4)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (3279mAh)', 'charging_watt': 20.0, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 14 Plus', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 1469234.0, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 4323, 'screen_inches': 6.7, 'camera_mp': 12.0, 'price_usd': 899.0, 'weight_g': 203.0, 'ideal_score': 59.58, 'processor_model': 'Apple A15 Bionic', 'ram_type': '6GB LPDDR4X', 'storage_type': '128GB/256GB/512GB NVMe', 'camera_sensor_main': 'Samsung S5K3L6 (12MP f/1.5)', 'camera_sensor_ultra': 'Samsung ISOCELL JN1 (12MP f/2.4)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (4325mAh)', 'charging_watt': 20.0, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 14 Pro', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 1469234.0, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 3200, 'screen_inches': 6.1, 'camera_mp': 48.0, 'price_usd': 999.0, 'weight_g': 206.0, 'ideal_score': 54.49, 'processor_model': 'Apple A16 Bionic', 'ram_type': '6GB LPDDR5', 'storage_type': '128GB/256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX 803 (48MP f/1.78)', 'camera_sensor_ultra': 'Sony IMX 553 (12MP f/2.4)', 'camera_sensor_telephoto': 'Samsung S5K3L6 (12MP f/2.8 3x)', 'battery_tech': 'Li-Ion (3200mAh)', 'charging_watt': 20.0, 'display_type': 'Super Retina XDR LTPO OLED', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 14 Pro Max', 'batch_number': 'IMPORT-2022', 'category': 'Smartphone', 'processor_score': 1469234.0, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 4323, 'screen_inches': 6.7, 'camera_mp': 48.0, 'price_usd': 1099.0, 'weight_g': 240.0, 'ideal_score': 60.22, 'processor_model': 'Apple A16 Bionic', 'ram_type': '6GB LPDDR5', 'storage_type': '128GB/256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX 803 (48MP f/1.78)', 'camera_sensor_ultra': 'Sony IMX 553 (12MP f/2.4)', 'camera_sensor_telephoto': 'Samsung S5K3L6 (12MP f/2.8 3x)', 'battery_tech': 'Li-Ion (4323mAh)', 'charging_watt': 20.0, 'display_type': 'Super Retina XDR LTPO OLED', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 15', 'batch_number': 'IMPORT-2023', 'category': 'Smartphone', 'processor_score': 1533780.0, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 3349, 'screen_inches': 6.1, 'camera_mp': 48.0, 'price_usd': 799.0, 'weight_g': 171.0, 'ideal_score': 62.82, 'processor_model': 'Apple A17 Pro', 'ram_type': '6GB LPDDR5X', 'storage_type': '256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX 803 (48MP f/1.6)', 'camera_sensor_ultra': 'Samsung ISOCELL JN1 (12MP f/2.4)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (3349mAh)', 'charging_watt': 20.0, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 15 Plus', 'batch_number': 'IMPORT-2023', 'category': 'Smartphone', 'processor_score': 1533780.0, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 4383, 'screen_inches': 6.7, 'camera_mp': 48.0, 'price_usd': 899.0, 'weight_g': 201.0, 'ideal_score': 67.51, 'processor_model': 'Apple A17 Pro', 'ram_type': '6GB LPDDR5X', 'storage_type': '128GB/256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX 803 (48MP f/1.6)', 'camera_sensor_ultra': 'Samsung ISOCELL JN1 (12MP f/2.4)', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Ion (4852mAh)', 'charging_watt': 20.0, 'display_type': 'Super Retina XDR OLED', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 15 Pro', 'batch_number': 'IMPORT-2023', 'category': 'Smartphone', 'processor_score': 1693091.0, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 3210, 'screen_inches': 6.3, 'camera_mp': 48.0, 'price_usd': 999.0, 'weight_g': 187.0, 'ideal_score': 69.3, 'processor_model': 'Apple A17 Pro', 'ram_type': '8GB LPDDR5X', 'storage_type': '128GB/256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX 906 (48MP f/1.78)', 'camera_sensor_ultra': 'Samsung ISOCELL JN1 (12MP f/2.4)', 'camera_sensor_telephoto': 'Samsung S5K3L6 (12MP f/2.8 3x)', 'battery_tech': 'Li-Ion (3349mAh)', 'charging_watt': 20.0, 'display_type': 'Super Retina XDR LTPO OLED', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 15 Pro Max', 'batch_number': 'IMPORT-2023', 'category': 'Smartphone', 'processor_score': 1693091.0, 'ram_gb': 8, 'storage_gb': 256, 'battery_mah': 5400, 'screen_inches': 6.7, 'camera_mp': 48.0, 'price_usd': 1299.0, 'weight_g': 221.0, 'ideal_score': 78.07, 'processor_model': 'Apple A17 Pro', 'ram_type': '8GB LPDDR5X', 'storage_type': '256GB/512GB/1TB NVMe', 'camera_sensor_main': 'Sony IMX 906 (48MP f/1.78)', 'camera_sensor_ultra': 'Samsung ISOCELL JN1 (12MP f/2.4)', 'camera_sensor_telephoto': 'Samsung S5K3L6 (12MP f/2.8 5x)', 'battery_tech': 'Li-Ion (4685mAh)', 'charging_watt': 20.0, 'display_type': 'Super Retina XDR LTPO OLED', 'refresh_rate_hz': 120},
    {'company_name': 'Apple', 'product_name': 'iPhone 16', 'batch_number': 'IMPORT-2024', 'category': 'Smartphone', 'processor_score': 1643390.0, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 3400, 'screen_inches': 6.3, 'camera_mp': 48.0, 'price_usd': 799.0, 'weight_g': 174.0, 'ideal_score': 66.97, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 16 Plus', 'batch_number': 'IMPORT-2024', 'category': 'Smartphone', 'processor_score': 1643390.0, 'ram_gb': 6, 'storage_gb': 256, 'battery_mah': 4400, 'screen_inches': 6.9, 'camera_mp': 48.0, 'price_usd': 899.0, 'weight_g': 205.0, 'ideal_score': 75.4, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 16e', 'batch_number': 'IMPORT-2024', 'category': 'Smartphone', 'processor_score': 1643390.0, 'ram_gb': 6, 'storage_gb': 128, 'battery_mah': 3100, 'screen_inches': 6.1, 'camera_mp': 48.0, 'price_usd': 699.0, 'weight_g': 168.0, 'ideal_score': 63.7, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 16 Pro', 'batch_number': 'IMPORT-2024', 'category': 'Smartphone', 'processor_score': 1643390.0, 'ram_gb': 8, 'storage_gb': 256, 'battery_mah': 3650, 'screen_inches': 6.3, 'camera_mp': 48.0, 'price_usd': 1099.0, 'weight_g': 189.0, 'ideal_score': 72.54, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 16 Pro Max', 'batch_number': 'IMPORT-2024', 'category': 'Smartphone', 'processor_score': 1643390.0, 'ram_gb': 8, 'storage_gb': 256, 'battery_mah': 5080, 'screen_inches': 6.9, 'camera_mp': 48.0, 'price_usd': 1299.0, 'weight_g': 235.0, 'ideal_score': 76.32, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone Air', 'batch_number': 'IMPORT-2024', 'category': 'Smartphone', 'processor_score': 1469234.0, 'ram_gb': 6, 'storage_gb': 256, 'battery_mah': 3400, 'screen_inches': 6.1, 'camera_mp': 48.0, 'price_usd': 899.0, 'weight_g': 170.0, 'ideal_score': 65.32, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 17', 'batch_number': 'IMPORT-2025', 'category': 'Smartphone', 'processor_score': 2033552.0, 'ram_gb': 6, 'storage_gb': 256, 'battery_mah': 3200, 'screen_inches': 6.1, 'camera_mp': 48.0, 'price_usd': 799.0, 'weight_g': 177.0, 'ideal_score': 70.55, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 17 Pro', 'batch_number': 'IMPORT-2025', 'category': 'Smartphone', 'processor_score': 2033552.0, 'ram_gb': 12, 'storage_gb': 256, 'battery_mah': 3900, 'screen_inches': 6.3, 'camera_mp': 48.0, 'price_usd': 1099.0, 'weight_g': 203.0, 'ideal_score': 77.4, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Apple', 'product_name': 'iPhone 17 Pro Max', 'batch_number': 'IMPORT-2025', 'category': 'Smartphone', 'processor_score': 2033552.0, 'ram_gb': 12, 'storage_gb': 512, 'battery_mah': 5088, 'screen_inches': 6.9, 'camera_mp': 48.0, 'price_usd': 1299.0, 'weight_g': 233.0, 'ideal_score': 83.74, 'processor_model': 'Apple A-series', 'ram_type': 'LPDDR4X/5X', 'storage_type': 'NVMe SSD', 'camera_sensor_main': 'Sony/Samsung', 'camera_sensor_ultra': 'Samsung ISOCELL', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 20.0, 'display_type': 'OLED/IPS', 'refresh_rate_hz': 60},
    {'company_name': 'Realme', 'product_name': 'Realme GT Neo 3T', 'batch_number': 'RMX3371', 'category': 'Smartphone', 'processor_score': 85.0, 'ram_gb': 8, 'storage_gb': 128, 'battery_mah': 5000, 'screen_inches': 6.62, 'camera_mp': 64.0, 'price_usd': 399.0, 'weight_g': 195.0, 'ideal_score': 63.56, 'processor_model': 'Qualcomm Snapdragon 870 5G', 'ram_type': 'LPDDR4X', 'storage_type': 'UFS 3.1', 'camera_sensor_main': '64MP Sony IMX682', 'camera_sensor_ultra': '8MP Ultrawide', 'camera_sensor_telephoto': None, 'battery_tech': 'Li-Po', 'charging_watt': 80.0, 'display_type': 'E4 AMOLED, 120Hz, HDR10+', 'refresh_rate_hz': 120},
]

# Default admin/producer accounts
SEED_USERS = [
    {'username': 'admin', 'password': 'admin123', 'role': 'producer', 'company_name': 'Apple'},
    {'username': 'samsung_admin', 'password': 'samsung123', 'role': 'producer', 'company_name': 'Samsung'},
    {'username': 'realme_admin', 'password': 'realme123', 'role': 'producer', 'company_name': 'Realme'},
]
